# Los Angeles Traffic Collision Data Cleaning
---

## Summary:
1. Import Modules and Data
2. Data Exploration
3. Data Cleaning
    1. Drop Useless Columns
    2. Drop Null Values
    3. Rename Columns
    4. Map Ethnicities
    5. Map Genders
4. Export Clean Data
    

Data Source: https://data.lacity.org/A-Safe-City/Traffic-Collision-Data-from-2010-to-Present/d5tf-ez2w

## 1. Import Modules and Data

In [1]:
import pandas as pd

# Read csv file
df = pd.read_csv("Data/raw_data/traffic-collision-data-from-2010-to-present.csv")
df.head()

,DR Number,Date Reported,Date Occurred,Time Occurred,Area ID,Area Name,Reporting District,Crime Code,Crime Code Description,MO Codes,...,Premise Description,Address,Cross Street,Location,Zip Codes,Census Tracts,Precinct Boundaries,LA Specific Plans,Council Districts,Neighborhood Councils (Certified)
0,191912240,2019-06-22T00:00:00.000,2019-06-22T00:00:00.000,1150,19,Mission,1985,997,TRAFFIC COLLISION,NaN,...,STREET,PARTHENIA ST,TOBIAS AV,"{'latitude': '34.2279', 'human_address': '{""ad...",19730.0,144.0,417.0,NaN,3.0,59.0
1,190315354,2019-06-22T00:00:00.000,2019-06-22T00:00:00.000,1600,3,Southwest,357,997,TRAFFIC COLLISION,NaN,...,STREET,JEFFERSON,CATALINA,"{'latitude': '34.0255', 'human_address': '{""ad...",22724.0,691.0,913.0,7.0,14.0,32.0
2,191011360,2019-06-22T00:00:00.000,2019-06-22T00:00:00.000,650,10,West Valley,1001,997,TRAFFIC COLLISION,NaN,...,STREET,ROSCOE,SHIRLEY,"{'latitude': '34.2204', 'human_address': '{""ad...",18909.0,101.0,1545.0,NaN,2.0,65.0
3,192111796,2019-06-22T00:00:00.000,2019-06-22T00:00:00.000,525,21,Topanga,2145,997,TRAFFIC COLLISION,NaN,...,STREET,VICTORY BL,SHOUP AV,"{'latitude': '34.1865', 'human_address': '{""ad...",4278.0,297.0,1473.0,NaN,4.0,49.0
4,191512949,2019-06-22T00:00:00.000,2019-06-22T00:00:00.000,245,15,N Hollywood,1543,997,TRAFFIC COLLISION,NaN,...,STREET,LAUREL CANYON BL,MAGNOLIA BL,"{'latitude': '34.1649', 'human_address': '{""ad...",8890.0,205.0,1332.0,17.0,5.0,39.0

## 2. Data Exploration
---

In [2]:
# Explore data-set to see what columns exist and their respective data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 477377 entries, 0 to 477376
Data columns (total 24 columns):
DR Number                            477377 non-null int64
Date Reported                        477377 non-null object
Date Occurred                        477377 non-null object
Time Occurred                        477377 non-null int64
Area ID                              477377 non-null int64
Area Name                            477377 non-null object
Reporting District                   477377 non-null int64
Crime Code                           477377 non-null int64
Crime Code Description               477377 non-null object
MO Codes                             392557 non-null object
Victim Age                           399952 non-null float64
Victim Sex                           470422 non-null object
Victim Descent                       469708 non-null object
Premise Code                         477352 non-null float64
Premise Description                  477352 non-null object
Address                              477377 non-null object
Cross Street                         456189 non-null object
Location                             477377 non-null object
Zip Codes                            476984 non-null float64
Census Tracts                        470912 non-null float64
Precinct Boundaries                  474312 non-null float64
LA Specific Plans                    175632 non-null float64
Council Districts                    471711 non-null float64
Neighborhood Councils (Certified)    453529 non-null float64
dtypes: float64(8), int64(5), object(11)
memory usage: 87.4+ MB

## 3. Data Cleaning

### a) Drop Useless Columns

In [3]:
# Drop columns that will not help during the analysis
drop_columns_df = df.drop(columns=[
    "DR Number", # Not useful for analysis
    "Date Reported", # More interested in Date Occured
    "Area ID", # Could use Area Name
    "Crime Code", # Uniform data: "997"
    "Crime Code Description", # Uniform data: "TRAFFIC COLLISION"
    "MO Codes", # Too many null values
    "Premise Code", # Could use Premise Description
    "Cross Street"]) # Could use Address or Location

drop_columns_df.head()

,Date Occurred,Time Occurred,Area Name,Reporting District,Victim Age,Victim Sex,Victim Descent,Premise Description,Address,Location,Zip Codes,Census Tracts,Precinct Boundaries,LA Specific Plans,Council Districts,Neighborhood Councils (Certified)
0,2019-06-22T00:00:00.000,1150,Mission,1985,32.0,M,H,STREET,PARTHENIA ST,"{'latitude': '34.2279', 'human_address': '{""ad...",19730.0,144.0,417.0,NaN,3.0,59.0
1,2019-06-22T00:00:00.000,1600,Southwest,357,27.0,M,H,STREET,JEFFERSON,"{'latitude': '34.0255', 'human_address': '{""ad...",22724.0,691.0,913.0,7.0,14.0,32.0
2,2019-06-22T00:00:00.000,650,West Valley,1001,20.0,F,H,STREET,ROSCOE,"{'latitude': '34.2204', 'human_address': '{""ad...",18909.0,101.0,1545.0,NaN,2.0,65.0
3,2019-06-22T00:00:00.000,525,Topanga,2145,44.0,F,H,STREET,VICTORY BL,"{'latitude': '34.1865', 'human_address': '{""ad...",4278.0,297.0,1473.0,NaN,4.0,49.0
4,2019-06-22T00:00:00.000,245,N Hollywood,1543,43.0,F,H,STREET,LAUREL CANYON BL,"{'latitude': '34.1649', 'human_address': '{""ad...",8890.0,205.0,1332.0,17.0,5.0,39.0

### b) Drop Null Values

In [4]:
# See how many null values exist for each column
pd.isnull(drop_columns_df).sum()

Date Occurred                             0
Time Occurred                             0
Area Name                                 0
Reporting District                        0
Victim Age                            77425
Victim Sex                             6955
Victim Descent                         7669
Premise Description                      25
Address                                   0
Location                                  0
Zip Codes                               393
Census Tracts                          6465
Precinct Boundaries                    3065
LA Specific Plans                    301745
Council Districts                      5666
Neighborhood Councils (Certified)     23848
dtype: int64

In [5]:
# Drop all null values
drop_nulls_df = drop_columns_df.dropna()

In [6]:
# Check row counts for each column after dropping nulls
drop_nulls_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 132467 entries, 1 to 477375
Data columns (total 16 columns):
Date Occurred                        132467 non-null object
Time Occurred                        132467 non-null int64
Area Name                            132467 non-null object
Reporting District                   132467 non-null int64
Victim Age                           132467 non-null float64
Victim Sex                           132467 non-null object
Victim Descent                       132467 non-null object
Premise Description                  132467 non-null object
Address                              132467 non-null object
Location                             132467 non-null object
Zip Codes                            132467 non-null float64
Census Tracts                        132467 non-null float64
Precinct Boundaries                  132467 non-null float64
LA Specific Plans                    132467 non-null float64
Council Districts                    132467 non-null float64
Neighborhood Councils (Certified)    132467 non-null float64
dtypes: float64(7), int64(2), object(7)
memory usage: 17.2+ MB

### c) Rename Columns

In [7]:
# Rename columns without spaces
rename_columns_df = drop_nulls_df.rename(columns={
    "Date Occurred" : "date",
    "Time Occurred" : "time",
    "Area Name" : "area",
    "Reporting District" : "district",
    "Victim Age" : "victim_age",
    "Victim Sex" : "victim_sex",
    "Victim Descent" : "victim_race",
    "Premise Description" : "premise",
    "Address" : "address",
    "Location" : "location"})

rename_columns_df.head()

,date,time,area,district,victim_age,victim_sex,victim_race,premise,address,location,Zip Codes,Census Tracts,Precinct Boundaries,LA Specific Plans,Council Districts,Neighborhood Councils (Certified)
1,2019-06-22T00:00:00.000,1600,Southwest,357,27.0,M,H,STREET,JEFFERSON,"{'latitude': '34.0255', 'human_address': '{""ad...",22724.0,691.0,913.0,7.0,14.0,32.0
4,2019-06-22T00:00:00.000,245,N Hollywood,1543,43.0,F,H,STREET,LAUREL CANYON BL,"{'latitude': '34.1649', 'human_address': '{""ad...",8890.0,205.0,1332.0,17.0,5.0,39.0
26,2019-06-21T00:00:00.000,1550,Rampart,238,23.0,M,W,STREET,1400 COURT ST,"{'latitude': '34.0647', 'human_address': '{""ad...",23444.0,548.0,397.0,54.0,11.0,31.0
29,2019-06-21T00:00:00.000,1010,Rampart,269,35.0,F,B,STREET,8TH ST,"{'latitude': '34.0496', 'human_address': '{""ad...",23078.0,568.0,1378.0,54.0,11.0,68.0
36,2019-06-21T00:00:00.000,40,Southwest,362,25.0,M,H,STREET,MARTIN LUTHER KING JR BL,"{'latitude': '34.0176', 'human_address': '{""ad...",22725.0,763.0,1024.0,7.0,12.0,54.0

### d) Map Ethnicities

Ethnicity Map Documentation: https://data.lacity.org/A-Safe-City/Traffic-Collision-Data-from-2010-to-Present/d5tf-ez2w

In [8]:
# Map each respective ethnicity inital into ethnicity groups
race_dict = {'H':'Hispanic', 'B':'Black', 'O':'Unknown', 'W':'White', 'X':'Unknown', '-':'Unknown',
             'A':'Asian', 'K':'Asian', 'C':'Asian', 'F':'Asian', 'U':'Pacific Islander',
             'J':'Asian', 'P':'Pacific Islander', 'V':'Asian', 'Z':'Asian',
             'I':'American Indian', 'G':'Pacific Islander', 'S':'Pacific Islander', 'D':'Asian', 'L':'Asian'}

rename_columns_df["victim_race"] = rename_columns_df["victim_race"].map(race_dict)

map_ethnicities_df = rename_columns_df
map_ethnicities_df.head()

,date,time,area,district,victim_age,victim_sex,victim_race,premise,address,location,Zip Codes,Census Tracts,Precinct Boundaries,LA Specific Plans,Council Districts,Neighborhood Councils (Certified)
1,2019-06-22T00:00:00.000,1600,Southwest,357,27.0,M,Hispanic,STREET,JEFFERSON,"{'latitude': '34.0255', 'human_address': '{""ad...",22724.0,691.0,913.0,7.0,14.0,32.0
4,2019-06-22T00:00:00.000,245,N Hollywood,1543,43.0,F,Hispanic,STREET,LAUREL CANYON BL,"{'latitude': '34.1649', 'human_address': '{""ad...",8890.0,205.0,1332.0,17.0,5.0,39.0
26,2019-06-21T00:00:00.000,1550,Rampart,238,23.0,M,White,STREET,1400 COURT ST,"{'latitude': '34.0647', 'human_address': '{""ad...",23444.0,548.0,397.0,54.0,11.0,31.0
29,2019-06-21T00:00:00.000,1010,Rampart,269,35.0,F,Black,STREET,8TH ST,"{'latitude': '34.0496', 'human_address': '{""ad...",23078.0,568.0,1378.0,54.0,11.0,68.0
36,2019-06-21T00:00:00.000,40,Southwest,362,25.0,M,Hispanic,STREET,MARTIN LUTHER KING JR BL,"{'latitude': '34.0176', 'human_address': '{""ad...",22725.0,763.0,1024.0,7.0,12.0,54.0

### e) Map Genders

In [9]:
# Map each gender inital into gender groups
map_gender_df = map_ethnicities_df # Set mapped ethnicities equal to a new gender df

gender_dict = {
    'M':'Male', 
    'F':'Female', 
    'X':'Unknown', 
    'H':'Unknown', 
    'N':'Unknown'}

map_gender_df["victim_sex"] = map_gender_df["victim_sex"].map(gender_dict)
map_gender_df.head()

,date,time,area,district,victim_age,victim_sex,victim_race,premise,address,location,Zip Codes,Census Tracts,Precinct Boundaries,LA Specific Plans,Council Districts,Neighborhood Councils (Certified)
1,2019-06-22T00:00:00.000,1600,Southwest,357,27.0,Male,Hispanic,STREET,JEFFERSON,"{'latitude': '34.0255', 'human_address': '{""ad...",22724.0,691.0,913.0,7.0,14.0,32.0
4,2019-06-22T00:00:00.000,245,N Hollywood,1543,43.0,Female,Hispanic,STREET,LAUREL CANYON BL,"{'latitude': '34.1649', 'human_address': '{""ad...",8890.0,205.0,1332.0,17.0,5.0,39.0
26,2019-06-21T00:00:00.000,1550,Rampart,238,23.0,Male,White,STREET,1400 COURT ST,"{'latitude': '34.0647', 'human_address': '{""ad...",23444.0,548.0,397.0,54.0,11.0,31.0
29,2019-06-21T00:00:00.000,1010,Rampart,269,35.0,Female,Black,STREET,8TH ST,"{'latitude': '34.0496', 'human_address': '{""ad...",23078.0,568.0,1378.0,54.0,11.0,68.0
36,2019-06-21T00:00:00.000,40,Southwest,362,25.0,Male,Hispanic,STREET,MARTIN LUTHER KING JR BL,"{'latitude': '34.0176', 'human_address': '{""ad...",22725.0,763.0,1024.0,7.0,12.0,54.0

## 4. Export Clean Data

In [10]:
# Export cleaned data set into a csv file
map_gender_df.to_csv("data/clean_data/clean_data.csv")