In [2]:
#import modules for the analysis environment
import os
import matplotlib.pyplot as plta
import pandas as pd
import numpy as np
import requests
import time
import ast

#read cleaned csv file
file_path = "Data/Clean/cleaned_data.csv"
df = pd.read_csv(file_path)
df.head()

,date,time,area,district,victim_Age,victim_sex,victim_race,premise,address,cross_street,zip,coordinates
0,2019-06-22T00:00:00.000,1150,Mission,1985,32.0,M,Hispanic,101.0,PARTHENIA ST,TOBIAS AV,19730.0,"{'latitude': '34.2279', 'longitude': '-118.4516'}"
1,2019-06-22T00:00:00.000,1600,Southwest,357,27.0,M,Hispanic,101.0,JEFFERSON,CATALINA,22724.0,"{'latitude': '34.0255', 'longitude': '-118.2937'}"
2,2019-06-22T00:00:00.000,650,West Valley,1001,20.0,F,Hispanic,101.0,ROSCOE,SHIRLEY,18909.0,"{'latitude': '34.2204', 'longitude': '-118.5579'}"
3,2019-06-22T00:00:00.000,525,Topanga,2145,44.0,F,Hispanic,101.0,VICTORY BL,SHOUP AV,4278.0,"{'latitude': '34.1865', 'longitude': '-118.6146'}"
4,2019-06-22T00:00:00.000,245,N Hollywood,1543,43.0,F,Hispanic,101.0,LAUREL CANYON BL,MAGNOLIA BL,8890.0,"{'latitude': '34.1649', 'longitude': '-118.3965'}"